### ISSUE TITLE
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

### ISSUE THREAD

**Issue by defendergz** [danielTobon43/DBScan-PCL-Optimized#1]
hi, i am going to compile this program,but i got some error:

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PCL_VISUALIZATION_LIBRARY (ADVANCED)
    linked by target "dbscan" in directory /home/gz/catkin_ws/src/DBScan-PCL-Optimized-master
-- Configuring incomplete, errors occurred!

pcl-1.9 
ros:kinetic
ubuntu 16.04

reproduce:

1.git clone your code,and put it at /home/xx/DBScan-PCL-Optimized(your code)
2. cd /home/xx/DBScan-PCL-Optimized(your code)
3 Set  PCL Build DIR in CMakeList.txt :
in my pc,pcl build path is : ~/pcl/release,so i modified CMakeList.txt in your program,like this:(line 21)
![00](https://user-images.githubusercontent.com/37363725/56018907-f5343500-5d35-11e9-9a95-bd737800be05.png)

3. mkdir build && cd build
4. cmake ..
then i got the error above, .
anyone can help me??thanks

**Comment by ghost** [comment]
Good day. I think may be the error is in the linking library part, try replacing:

```
##############################################################################
# TARGET LIBRARIES
##############################################################################
target_link_libraries(${PROJECT_NAME}  ${PCL_COMMON_LIBRARIES} ${PCL_IO_LIBRARIES} ${PCL_VISUALIZATION_LIBRARY})
```

with:

```
##############################################################################
# TARGET LIBRARIES
##############################################################################
target_link_libraries(${PROJECT_NAME}  ${PCL_LIBRARIES})
```

**Comment by ghost** [comment]
By the way, the pcl build path should not end with "/", just: `set(PCL_DIR /home/gz/pcl/release)`

**Comment by defendergz** [comment]
hi!
thank u reply! after i modified cmakelist.txt:
in line 20:
![Screenshot from 2019-04-27 16-13-13](https://user-images.githubusercontent.com/37363725/56846900-6283c080-6907-11e9-8e2c-78f41b578655.png)
and in line 89,added boost_system boost_filesystem ${PCL_LIBRARIES}:
![Screenshot from 2019-04-27 16-14-18](https://user-images.githubusercontent.com/37363725/56846914-89da8d80-6907-11e9-87da-512e4bd7d9b5.png)
i cmake .. && make correctly.and run this ./dbscan .......everything is ok.
but a few days later, it doesn't work.so i delete all dir/file in build.and recompile.
`cmake ..` is ok, but when run `make`, i got some error:
``Scanning dependencies of target dbscan
CMakeFiles/dbscan.dir/main.cpp.o: In function `readCloudFromFile(int, char**, std::vector<htr::Point3D, std::allocator<htr::Point3D> >&, boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&)':
main.cpp:(.text+0x1322): undefined reference to `pcl::io::loadPolygonFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pcl::PolygonMesh&)'
collect2: error: ld returned 1 exit status
CMakeFiles/dbscan.dir/build.make:366: recipe for target 'bin/dbscan' failed
make[2]: *** [bin/dbscan] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dbscan.dir/all' failed
make[1]: *** [CMakeFiles/dbscan.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
``
could u plz help me fix it? thank u.

**Comment by ghost** [comment]
Again, it is a problem of linking pcl correctly. I'm going to leave the general version of the CMakeList.txt project on GitHub. Go back to download again DBScan from the GitHub and try to compile it.

**Comment by ghost** [comment]
When you compile the project with cmake, verify that the pcl include part (which is printed on the terminal) comes from your PCL_dir and not from the pcl of ROS

**Comment by ghost** [comment]
If you use: `${PCL_LIBRARIES}` it is not necessary the link to Boost library (pcl already does)
