### ISSUE TITLE
VTK package

### ISSUE THREAD

**Issue by wwtinwhu** [danielTobon43/DBScan-PCL-Optimized#10]
Hello, @danielTobon43 . Thanks for your excellent work! Is this the VTK? https://github.com/Kitware/VTK. I need update this lib to at least 8.1

**Comment by ghost** [comment]
Hi @wwtinwhu, what do you mean if this is vtk? 

This project is a dbscan clustering algorithm that uses [Point Cloud Library](https://pointclouds.org/). Point Cloud Library is a Library that depends on [VTK](https://github.com/Kitware/VTK).

**Comment by wwtinwhu** [comment]
> Hi @wwtinwhu, what do you mean if this is vtk?
> 
> This project is a dbscan clustering algorithm that uses [Point Cloud Library](https://pointclouds.org/). Point Cloud Library is a Library that depends on [VTK](https://github.com/Kitware/VTK).

Get it! Thanks, @danielTobon43 !
