### ISSUE TITLE
run docker fails

### ISSUE THREAD

**Issue by xctest** [danielTobon43/DBScan-PCL-Optimized#15]
Hi, when I run docker like this:

> sudo docker run --rm -it \
>            --volume=/tmp/.X11-unix:/tmp/.X11-unix:rw \
>            --volume=/tmp/.docker.xauth:/tmp/.docker.xauth:rw \
>            --env="XAUTHORITY=/tmp/.docker.xauth" \
>            --env="DISPLAY" \
>            --name="dbscan" \
>            --cap-add sys_ptrace \
>            -p 127.0.0.1:2222:22 \
>            --volume=/path/to/my/pcd/dir:/tmp \
>            -t ghcr.io/danieltobon43/dbscan-octrees:latest --cloudfile /tmp/1652257579.725173473.pcd

I got an error:
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "app": executable file not found in $PATH: unknown.

any suggestions would be appriciated

**Comment by ghost** [comment]
> Hi, when I run docker like this:
> 
> > sudo docker run --rm -it 
> > --volume=/tmp/.X11-unix:/tmp/.X11-unix:rw 
> > --volume=/tmp/.docker.xauth:/tmp/.docker.xauth:rw 
> > --env="XAUTHORITY=/tmp/.docker.xauth" 
> > --env="DISPLAY" 
> > --name="dbscan" 
> > --cap-add sys_ptrace 
> > -p 127.0.0.1:2222:22 
> > --volume=/path/to/my/pcd/dir:/tmp 
> > -t ghcr.io/danieltobon43/dbscan-octrees:latest --cloudfile /tmp/1652257579.725173473.pcd
> 
> I got an error: docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "app": executable file not found in $PATH: unknown.
> 
> any suggestions would be appriciated

Hi @xctest thanks for reporting this. Indeed there is an issue with the docker image for ubuntu. It seems related to this issue #https://github.com/actions/upload-artifact/issues/38 I will update the image to fix this. I will let you know when is done.

**Comment by ghost** [comment]
@xctest I have released a new version

`docker pull ghcr.io/danieltobon43/dbscan-octrees:sha-467d298`

please let me know if works as expected. I will update the latest version later.

```control
sudo docker run --rm -it \
--volume=/tmp/.X11-unix:/tmp/.X11-unix:rw \
--volume=/tmp/.docker.xauth:/tmp/.docker.xauth:rw \
--env="XAUTHORITY=/tmp/.docker.xauth" \
--env="DISPLAY" \
--name="dbscan" \
--volume=/path/to/my/pcd/dir:/tmp \
-t ghcr.io/danieltobon43/dbscan-octrees:sha-467d298 --cloudfile /tmp/1652257579.725173473.pcd
```

**Comment by xctest** [comment]
thanks a lot for your help, i will try it 👍
